feat : 문제 랜덤하게 가져오는 로직 추가
SW13-Monstera/backend pull request #100
Opened 2023-04-09 10:32 UTC by ekzm8523

문제 랜덤 추출 QueryParams 추가 및 메서드 분리

### Issue Number

close: MSTR-413

### 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] 문제 검색시 쿼리파람으로 shuffle flag와 랜덤 시드를 입력받을 수 있도록 추가 (메인 페이지, 모든 문제 보기에서 활용 가능)
- [x] findProblemsByQuery 메서드 분리

### 변경사항

- 의존성 목록

### 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 리펙토링
- [ ] 문서 업데이트

### PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- default 값으로 `shuffle = false`, `seed = 42 `로 설정해놨습니다.
- `shuffle=false` 일 때 가장 최근에 생성된 문제가 먼저 보이도록 ordering을 해놓았습니다.

2023-04-09 11:02 UTC, kshired requested changes
@ekzm8523

2023-04-09 11:02 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/ProblemController.kt
>          pageable: Pageable,
Pageable 사용이 너무 스프링 JPA랑 강결합되는 것 같아서, 빼고 싶은데용.
그냥 @RequestParam 에서 page, size 받는 걸로 변경하는거 적용해주실 수 있나요?

Repository 클래스에서만 Pageable 사용하도록.

2023-04-09 11:26 UTC, ekzm8523 commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
> +        val ids = getPaginatedIds(totalProblemIds, problemSearchDto.pageable)
1. 일단 문제 수가 많지 않기 때문에 성능상은 이슈가 없을 것 같은데 예상되는 문제가 있으신가요?? (동시성??)
2. 일단 셔플링을 할 때 시드만 잘 고정하면 항상 같은 순열의 리스트를 반환하기 때문에 평소에는 문제가 없는데 엣지 케이스가 하나 있기는 해요. 그건 1번 페이지 받고 2번 페이지 부르려고 하기 전에 데이터가 추가되었을 때 셔플링이 새롭게 돌긴 합니다.
하지만 이 부분은 제대로 페이지네이션이 되지 않는 이슈라기보단 셔플링 기능 자체에 대한 이슈라서 얘기를 해보면 좋을 것 같기는 해요~!

2023-04-09 11:30 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
> +        val ids = getPaginatedIds(totalProblemIds, problemSearchDto.pageable)
@ekzm8523 

1. 뭔가 메모리에서 페이징 하는게 정석은 아니여서, 괜찮나 싶은건데용. 나중에 문제가 많아지면, 데이터를 가져오다가 서버가 full gc 돌다가 죽어버릴거 같아요. 그 때되서 문제 해결하려면, 좀 애매해질거 같습니당. 미리 대처해놓는건 어때요

2. 얘기해봐용~

2023-04-09 14:44 UTC, ekzm8523 commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
> +        val ids = getPaginatedIds(totalProblemIds, problemSearchDto.pageable)
@kshired 
우리 회의때 얘기하는걸 까먹었네요 ㅋㅋ
아니면 우리 메인페이지에 해당하는 문제를 위해서 shuffling problem을 뽑는 API를 하나 더 만들까요?

2023-04-09 15:46 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
> +        val ids = getPaginatedIds(totalProblemIds, problemSearchDto.pageable)
@ekzm8523 
네넹. 문제 검색하는 API는 일단 이전그대로 가고, 랜덤 N개 추출할 수 있는 API 하나 만들어주시면 될 듯.

2023-04-16 10:54 UTC, ekzm8523 commented
@kshired 랜덤하게 N개 문제 가져오는 API 뚫어놨습니다~!

2023-04-16 12:04 UTC, kshired reviewed
@ekzm8523 👀

2023-04-16 12:04 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepository.kt
> +    @Query("select problem_id from problem p order by RAND() limit :size", nativeQuery = true)
```suggestion
    @Query("select problem_id from problem order by RAND() limit :size", nativeQuery = true)
```

2023-04-16 12:04 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustom.kt
> +    fun getProblemId2StatMap(problems: List<Problem>): Map<Long?, GradingHistoryStats>
2 를 꼭 숫자를 써야할까유.. To 어떠신가용

2023-04-16 12:04 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
> +                it.problem.id
```suggestion
    override fun getProblemId2StatMap(problems: List<Problem>): Map<Long, GradingHistoryStats> =
        getGradingHistoriesRelatedProblems(problems)
            .groupBy {
                it.problem.id!!

```

2023-04-16 12:04 UTC, kshired commented on src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/ProblemControllerTest.kt
> +    fun `랜덤하게 N개 문제 가져오기`() {
테스트 추가는 good인데용

`src/docs/asciidoc/index.adoc` 에 추가해줘야 합니당.

2023-04-16 12:04 UTC, kshired commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
> +                it.problem.id
이미 저기까지 나온 id가 null일수는 없어서..

2023-04-16 14:10 UTC, ekzm8523 commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustom.kt
> +    fun getProblemId2StatMap(problems: List<Problem>): Map<Long?, GradingHistoryStats>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 스칼라에서 관습적으로 쓰는 방식이라 함 써봤어요

2023-04-16 14:10 UTC, ekzm8523 commented on src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustom.kt
> +    fun getProblemId2StatMap(problems: List<Problem>): Map<Long?, GradingHistoryStats>
로마에 오면 로마의 법을 따라아죠

2023-04-16 14:29 UTC, ekzm8523 commented
@kshired finished!!

2023-04-16 14:30 UTC, kshired approved these changes

2023-04-17 01:18 UTC, merged